SUBDIR=	apply basename cmp comm compress csplit ctags cut \
	diff diff3 doas less mg patch pr \
	sdiff sed shar signify tsort \
	uudecode uuencode vis what xinstall
include ${.TOPDIR}/mk/bsd.subdir.mk
